repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--select, I, --fix]   # optional: auto-fix issues
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pipenv run pyright
        language: system
        pass_filenames: false
        files: ^app/.*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: debug-statements
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        exclude: ^Pipfile\.lock$
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
