FROM python:3.11

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip install pipenv && \
    pipenv install --system --dev

COPY . .

CMD ["pipenv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--port", "3000"]