[project]
name = "slack-ray-translator"
description = "Straker Translate Slack App"
version = "1.0.0"
requires-python = ">= 3.11"
readme = "README.md"
authors = [{ name = "Straker", email = "developers@strakertranslations.com" }]
dependencies = []

[tool.ruff]
# Black formatter.
line-length = 88

[tool.ruff.lint]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B"]
# Never enforce `E501` (line length violations).
ignore = ["E501", "F841", "B039", "B007"]
# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
python_version = "3.11"
files = "app"
ignore_missing_imports = true
disable_error_code = ["no-redef"]
