[project]
name = "slack-ray-translator"
description = "Straker Translate Slack App"
version = "1.0.0"
requires-python = ">= 3.11"
readme = "README.md"
authors = [{ name = "Straker", email = "developers@strakertranslations.com" }]
dependencies = []

[tool.ruff]
# Black formatter.
line-length = 88

[tool.ruff.lint]
# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "B"]
# Never enforce `E501` (line length violations).
ignore = ["E501", "F841", "B039", "B007"]
# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

[tool.pyright]
pythonVersion = "3.11"
include = ["app"]
typeCheckingMode = "basic"
ignore = [
    "app/auth/connector.py",
    "app/routers/ray.py",
    "app/slack/listener_actions.py",
    "app/slack/listeners.py",
]
reportMissingImports = "none"
reportMissingTypeStubs = "none"
reportPrivateImportUsage = "none"
