/**
 * Render Block Kit JSON into a single self-contained HTML file.
 *
 * Reads output/blocks.json (generated by generate_blocks.py),
 * uses slack-blocks-to-jsx + React SSR to render each template,
 * and writes output/ui-catalog.html.
 *
 * Usage:
 *   node render.mjs
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { Message } from "slack-blocks-to-jsx";

/**
 * @typedef {import("slack-blocks-to-jsx").Block} SlackBlock
 * @typedef {"message" | "modal" | "home" | "text_only"} TemplateType
 * @typedef {"message" | "view"} TemplateKind
 * @typedef {{
 *   name: string,
 *   category: string,
 *   type: TemplateType,
 *   blocks?: SlackBlock[],
 *   text?: string,
 *   title?: string,
 * }} ExportTemplate
 * @typedef {ExportTemplate & { kind: TemplateKind }} RenderTemplate
 * @typedef {{
 *   total: number,
 *   total_messages: number,
 *   total_views: number,
 * }} ExportStats
 * @typedef {{
 *   messages: ExportTemplate[],
 *   views: ExportTemplate[],
 *   stats: ExportStats,
 * }} ExportCatalog
 * @typedef {{
 *   generated_at: string,
 *   default_language?: string,
 *   languages?: string[],
 *   catalogs?: Record<string, ExportCatalog>,
 *   messages: ExportTemplate[],
 *   views: ExportTemplate[],
 *   stats: ExportStats,
 * }} ExportData
 */

const require = createRequire(import.meta.url);
/** @type {{ emojify: (text: string) => string }} */
const emoji = require("node-emoji");

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * @param {string} name
 * @param {string} fallback
 * @returns {string}
 */
function argValue(name, fallback) {
  const index = process.argv.indexOf(name);
  if (index === -1 || index + 1 >= process.argv.length) return fallback;
  return process.argv[index + 1];
}

const blocksPath = argValue("--input", join(__dirname, "output", "blocks.json"));
const outputPath = argValue(
  "--output",
  join(__dirname, "output", "ui-catalog.html")
);
/** @type {ExportData & { subset?: { match?: string | null, names?: string[], categories?: string[] } }} */
const data = JSON.parse(readFileSync(blocksPath, "utf-8"));

/** @type {ExportCatalog} */
const legacyCatalog = {
  messages: data.messages,
  views: data.views,
  stats: data.stats,
};
const languageCodes =
  data.languages && data.languages.length > 0
    ? data.languages
    : [data.default_language || "en"];
const defaultLanguage = data.default_language || languageCodes[0] || "en";
const catalogs = data.catalogs || { [defaultLanguage]: legacyCatalog };
const isSubset = Boolean(data.subset);
const pageTitle = isSubset ? "Slack UI Catalog (subset)" : "Slack UI Catalog";
const subsetSummary = isSubset
  ? [
      data.subset?.match ? `match=${data.subset.match}` : null,
      data.subset?.names?.length
        ? `names=${data.subset.names.length}`
        : null,
      data.subset?.categories?.length
        ? `categories=${data.subset.categories.join(",")}`
        : null,
    ]
      .filter(Boolean)
      .join(" · ")
  : "";


// Read the slack-blocks-to-jsx stylesheet to inline
const libCssPath = join(
  __dirname,
  "node_modules",
  "slack-blocks-to-jsx",
  "dist",
  "style.css"
);
const libCss = readFileSync(libCssPath, "utf-8");

// Category display order
const categoryOrder = [
  "Auth",
  "Home",
  "Jobs",
  "Quotes",
  "Events",
  "Translation",
  "Video",
  "Quality",
  "FactCheck",
  "Modals",
  "Help",
  "Tokens",
  "Errors",
];

/**
 * @param {string} language
 * @returns {ExportCatalog}
 */
function getCatalog(language) {
  return catalogs[language] || legacyCatalog;
}

/**
 * @param {ExportCatalog} catalog
 * @returns {RenderTemplate[]}
 */
function getAllTemplates(catalog) {
  return [
    ...catalog.messages.map(
      (m) => /** @type {RenderTemplate} */ ({ ...m, kind: "message" })
    ),
    ...catalog.views.map(
      (v) => /** @type {RenderTemplate} */ ({ ...v, kind: "view" })
    ),
  ];
}

/**
 * @param {RenderTemplate[]} templates
 * @returns {Record<string, RenderTemplate[]>}
 */
function groupTemplates(templates) {
  /** @type {Record<string, RenderTemplate[]>} */
  const groupedTemplates = {};
  for (const t of templates) {
    if (!groupedTemplates[t.category]) groupedTemplates[t.category] = [];
    groupedTemplates[t.category].push(t);
  }
  return groupedTemplates;
}

/**
 * @param {Record<string, RenderTemplate[]>} groupedTemplates
 * @returns {string[]}
 */
function getSortedCategories(groupedTemplates) {
  const sorted = categoryOrder.filter((c) => groupedTemplates[c] !== undefined);
  for (const c of Object.keys(groupedTemplates)) {
    if (!sorted.includes(c)) sorted.push(c);
  }
  return sorted;
}

/**
 * @param {string} language
 * @param {string} category
 * @param {string} name
 * @returns {string}
 */
function templateId(language, category, name) {
  const langSlug = language.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const categorySlug = category.toLowerCase().replace(/\s+/g, "-");
  const templateSlug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `tpl-${langSlug}-${categorySlug}-${templateSlug}`;
}

// Work around slack-blocks-to-jsx emoji tokenizer bug (github.com/themashcodee/
// slack-blocks-to-jsx): the SlackEmojiTokenizer's findEndDelimiter greedily
// matches any pair of colons without checking whether the content between them
// is a valid emoji name.  Combined with the library's *bold* → **bold**
// conversion, patterns like "*Bold:*\n:emoji:" produce bogus tokens.
//
// Fix: convert Slack emoji shortcodes to Unicode *before* the library sees them
// using node-emoji (already a transitive dependency).
/** @type {Record<string, string>} */
const SLACK_EMOJI_FALLBACKS = {
  large_blue_circle: "\u{1F535}",
  large_green_circle: "\u{1F7E2}",
  large_orange_circle: "\u{1F7E0}",
  large_red_circle: "\u{1F534}",
  large_yellow_circle: "\u{1F7E1}",
  large_blue_square: "\u{1F7E6}",
  large_green_square: "\u{1F7E9}",
  large_orange_square: "\u{1F7E7}",
  large_red_square: "\u{1F7E5}",
  large_yellow_square: "\u{1F7E8}",
  sports_medal: "\u{1F3C5}",
  coin: "\u{1FA99}",
};

/**
 * @param {unknown} text
 * @returns {unknown}
 */
function sanitiseMrkdwn(text) {
  if (typeof text !== "string") return text;
  let result = emoji.emojify(text);
  result = result.replace(/:([a-z0-9_+-]+):/g, (match, name) => {
    return SLACK_EMOJI_FALLBACKS[name] || match;
  });
  return result;
}

/**
 * @param {SlackBlock[] | undefined} blocks
 * @returns {SlackBlock[] | undefined}
 */
function sanitiseBlocks(blocks) {
  if (!Array.isArray(blocks)) return blocks;
  return /** @type {SlackBlock[]} */ (
    JSON.parse(
    JSON.stringify(blocks, (key, value) => {
      if (key === "text" && typeof value === "string") return sanitiseMrkdwn(value);
      return value;
    })
    )
  );
}

// Render each template's blocks to HTML via React SSR
/**
 * @param {SlackBlock[] | undefined} blocks
 * @param {string} name
 * @returns {string}
 */
function renderBlocks(blocks, name) {
  blocks = sanitiseBlocks(blocks);
  if (!blocks || blocks.length === 0) return "<em>No blocks</em>";
  try {
    const el = createElement(Message, {
      blocks,
      name: "Straker Translate",
      logo: "https://avatars.slack-edge.com/2024-01-01/placeholder.png",
      withoutWrapper: false,
    });
    return renderToStaticMarkup(el);
  } catch (err) {
    return `<div class="render-error">Render error for ${name}: ${formatErrorMessage(err)}</div>`;
  }
}

/**
 * @param {unknown} error
 * @returns {string}
 */
function formatErrorMessage(error) {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

const defaultCatalog = getCatalog(defaultLanguage);
const defaultGrouped = groupTemplates(getAllTemplates(defaultCatalog));
const defaultSortedCategories = getSortedCategories(defaultGrouped);

const languageOptionsHtml = languageCodes
  .map(
    (language) =>
      `<option value="${language}" ${
        language === defaultLanguage ? "selected" : ""
      }>${language}</option>`
  )
  .join("");

// Build the nav sidebar HTML
let navHtml = "";
for (const language of languageCodes) {
  const catalog = getCatalog(language);
  const grouped = groupTemplates(getAllTemplates(catalog));
  const sortedCategories = getSortedCategories(grouped);
  navHtml += `<div class="language-nav ${
    language === defaultLanguage ? "" : "is-hidden"
  }" data-language="${language}">`;
  for (const cat of sortedCategories) {
    const slug = `${language.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${cat
      .toLowerCase()
      .replace(/\s+/g, "-")}`;
    const templates = grouped[cat] ?? [];
    navHtml += `<div class="nav-category">`;
    navHtml += `<a href="#cat-${slug}" class="nav-cat-link">${cat}</a>`;
    navHtml += `<div class="nav-items">`;
    for (const t of templates) {
      const id = templateId(language, cat, t.name);
      navHtml += `<a href="#${id}" class="nav-item">${t.name}</a>`;
    }
    navHtml += `</div></div>`;
  }
  navHtml += `</div>`;
}

// Build the main content
let contentHtml = "";
for (const language of languageCodes) {
  const catalog = getCatalog(language);
  const grouped = groupTemplates(getAllTemplates(catalog));
  const sortedCategories = getSortedCategories(grouped);
  contentHtml += `<div class="language-content ${
    language === defaultLanguage ? "" : "is-hidden"
  }" data-language="${language}">`;
  for (const cat of sortedCategories) {
    const slug = `${language.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${cat
      .toLowerCase()
      .replace(/\s+/g, "-")}`;
    const templates = grouped[cat] ?? [];
    contentHtml += `<div class="category-section" id="cat-${slug}">`;
    contentHtml += `<h2 class="category-title">${cat}</h2>`;
    for (const t of templates) {
      const id = templateId(language, cat, t.name);
      const typeLabel =
        t.type === "modal"
          ? "Modal"
          : t.type === "home"
          ? "Home Tab"
          : t.type === "text_only"
          ? "Text Only"
          : "Message";
      const rendered = renderBlocks(t.blocks, t.name);

      // For text-only messages, show the text content
      const textContent =
        typeof t.text === "string"
          ? `<div class="text-only-content">${t.text}</div>`
          : "";

      contentHtml += `
        <div class="template-card" id="${id}">
          <div class="template-header">
            <span class="template-name">${t.name}</span>
            <span class="template-type type-${typeLabel
              .toLowerCase()
              .replace(/\s+/g, "-")}">${typeLabel}</span>
          </div>
          <div class="template-body ${
            t.type === "modal" ? "modal-container" : ""
          }">
            ${
              t.type === "modal"
                ? `<div class="modal-chrome"><div class="modal-title-bar"><span class="modal-close-btn">×</span><span class="modal-title">${
                    t.title || ""
                  }</span><span class="modal-submit-btn">Submit</span></div><div class="modal-content">${rendered}</div></div>`
                : rendered
            }
            ${textContent}
          </div>
        </div>`;
    }
    contentHtml += `</div>`;
  }
  contentHtml += `</div>`;
}

// Assemble the full HTML
const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${pageTitle} — Straker Translate</title>
  <style>
    /* Inline the slack-blocks-to-jsx styles */
    ${libCss}

    /* Page layout */
    :root {
      --sidebar-width: 340px;
      --bg-primary: #1a1d21;
      --bg-secondary: #222529;
      --bg-content: #ffffff;
      --text-primary: #d1d2d3;
      --text-secondary: #ababad;
      --text-dark: #1d1c1d;
      --accent: #1264a3;
      --border: #383b3f;
      --card-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08);
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #f4f4f4;
      color: var(--text-dark);
      display: flex;
      min-height: 100vh;
    }

    /* Sidebar */
    .sidebar {
      position: fixed;
      top: 0;
      left: 0;
      width: var(--sidebar-width);
      height: 100vh;
      background: var(--bg-primary);
      color: var(--text-primary);
      overflow-y: auto;
      padding: 20px 0;
      z-index: 100;
    }
    .sidebar-title {
      padding: 0 16px 16px;
      font-size: 18px;
      font-weight: 900;
      color: #fff;
      border-bottom: 1px solid var(--border);
      margin-bottom: 12px;
    }
    .sidebar-stats {
      padding: 0 16px 12px;
      font-size: 12px;
      color: var(--text-secondary);
    }
    .language-control {
      padding: 0 16px 16px;
      border-bottom: 1px solid var(--border);
      margin-bottom: 12px;
    }
    .language-label {
      display: block;
      margin-bottom: 6px;
      font-size: 12px;
      color: var(--text-secondary);
    }
    .language-select {
      width: 100%;
      padding: 6px 8px;
      border-radius: 4px;
      border: 1px solid var(--border);
      background: var(--bg-secondary);
      color: var(--text-primary);
    }
    .is-hidden { display: none !important; }
    .nav-category { margin-bottom: 4px; }
    .nav-cat-link {
      display: block;
      padding: 6px 16px;
      font-size: 14px;
      font-weight: 700;
      color: var(--text-primary);
      text-decoration: none;
    }
    .nav-cat-link:hover { background: var(--bg-secondary); }
    .nav-items { padding-left: 12px; }
    .nav-item {
      display: block;
      padding: 3px 16px;
      font-size: 12px;
      color: var(--text-secondary);
      text-decoration: none;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .nav-item:hover { color: #fff; background: var(--bg-secondary); }

    /* Main content */
    .main {
      margin-left: var(--sidebar-width);
      flex: 1;
      padding: 32px 40px;
      max-width: 1000px;
    }
    .page-title {
      font-size: 28px;
      font-weight: 900;
      margin-bottom: 8px;
    }
    .page-subtitle {
      color: #616061;
      margin-bottom: 32px;
      font-size: 14px;
    }

    /* Category section */
    .category-section { margin-bottom: 48px; }
    .category-title {
      font-size: 20px;
      font-weight: 700;
      padding-bottom: 8px;
      border-bottom: 2px solid var(--accent);
      margin-bottom: 20px;
      color: var(--text-dark);
    }

    /* Template card */
    .template-card {
      background: var(--bg-content);
      border-radius: 8px;
      box-shadow: var(--card-shadow);
      margin-bottom: 20px;
      overflow: hidden;
    }
    .template-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 12px 16px;
      background: #f8f8f8;
      border-bottom: 1px solid #e8e8e8;
    }
    .template-name {
      font-size: 14px;
      font-weight: 700;
      color: var(--text-dark);
    }
    .template-type {
      font-size: 11px;
      padding: 2px 8px;
      border-radius: 10px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .type-message { background: #e8f5e9; color: #2e7d32; }
    .type-modal { background: #e3f2fd; color: #1565c0; }
    .type-home-tab { background: #f3e5f5; color: #7b1fa2; }
    .type-text-only { background: #fff3e0; color: #e65100; }

    .template-body {
      padding: 16px;
    }

    /* Text-only message display */
    .text-only-content {
      padding: 12px 16px;
      background: #f9f9f9;
      border-radius: 6px;
      border-left: 3px solid #1264a3;
      font-size: 14px;
      line-height: 1.5;
      color: #1d1c1d;
    }

    /* Modal chrome */
    .modal-container .modal-chrome {
      border: 1px solid #ddd;
      border-radius: 12px;
      overflow: hidden;
      max-width: 520px;
      margin: 0 auto;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }
    .modal-title-bar {
      background: #fff;
      padding: 12px 16px;
      display: flex;
      align-items: center;
      border-bottom: 1px solid #e8e8e8;
    }
    .modal-close-btn {
      font-size: 18px;
      color: #616061;
      cursor: default;
      margin-right: 12px;
    }
    .modal-title {
      flex: 1;
      font-weight: 700;
      font-size: 16px;
    }
    .modal-submit-btn {
      background: #007a5a;
      color: white;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 13px;
      font-weight: 600;
    }
    .modal-content {
      padding: 16px;
      background: #fff;
    }

    /* Render error */
    .render-error {
      padding: 12px;
      background: #fff3cd;
      border: 1px solid #ffc107;
      border-radius: 6px;
      color: #856404;
      font-size: 13px;
    }

    /* Override some slack-blocks-to-jsx defaults for better static display */
    .slack_blocks_to_jsx {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif !important;
    }
    .slack_blocks_to_jsx--header {
      display: none !important;
    }
  </style>
</head>
<body>
  <nav class="sidebar">
    <div class="sidebar-title">Straker Translate</div>
    <div class="sidebar-stats">
      ${defaultCatalog.stats.total} templates — ${defaultCatalog.stats.total_messages} messages, ${defaultCatalog.stats.total_views} views<br>
      Generated: ${new Date(data.generated_at).toLocaleDateString()}
    </div>
    <div class="language-control">
      <label class="language-label" for="language-select">Language</label>
      <select class="language-select" id="language-select">
        ${languageOptionsHtml}
      </select>
    </div>
    ${navHtml}
  </nav>
  <main class="main">
    <h1 class="page-title">${pageTitle}</h1>
    <p class="page-subtitle">
      ${
        isSubset
          ? `Focused subset of ${defaultCatalog.stats.total} Slack Block Kit templates under active review${
              subsetSummary ? ` (${subsetSummary})` : ""
            }.`
          : `All ${defaultCatalog.stats.total} Slack Block Kit templates rendered with mock data.`
      }
      ${defaultCatalog.stats.total_messages} messages and ${defaultCatalog.stats.total_views} views across
      ${defaultSortedCategories.length} categories.
    </p>
    ${contentHtml}
  </main>
  <script>
    const languageSelect = document.getElementById("language-select");
    function showLanguage(language) {
      document.querySelectorAll("[data-language]").forEach((element) => {
        element.classList.toggle("is-hidden", element.dataset.language !== language);
      });
    }
    languageSelect?.addEventListener("change", (event) => {
      const select = event.target;
      if (!(select instanceof HTMLSelectElement)) return;
      showLanguage(select.value);
      window.history.replaceState(null, "", "#");
      window.scrollTo({ top: 0, behavior: "auto" });
    });
  </script>
</body>
</html>`;

// Write output
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, html, "utf-8");

console.log(
  `Rendered ${defaultCatalog.stats.total} templates${
    isSubset ? " (subset)" : ""
  } -> ${outputPath}`
);
